# Generated by Django 4.0.5 on 2022-07-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facedata',
            field=models.BinaryField(null=True),
        ),
    ]
